SERIAL_DEV=/dev/ttyUSB0
ISP_DEV=0x378
ISP_PROG=dapa
AVRDUDE_BAUDRATE=115200
MCU=atmega328p
F_CPU=14745600
DEBUG=1
CFLAGS += -DBOOTLOADER_DDR=DDRB
CFLAGS += -DBOOTLOADER_PORT=PORTB
CFLAGS += -DBOOTLOADER_PIN=PINB
CFLAGS += -DBOOTLOADER_PINNUM=PINB0
CFLAGS += -DBOOTLOADER_JUMPER=1
CFLAGS += -DSEND_BOOT_MESSAGE=1
